/**
 * Table Schema Detector & Auto-Column Mapper
 * Analyzes CSV/XLSX/JSON headers and sample values to detect target database table
 * and auto-map columns with intelligent fuzzy matching.
 */

const TABLE_SCHEMAS = {
    users: {
        id: 'users',
        label: 'Students / Users (users)',
        targetEntity: 'student',
        fields: [
            { key: 'firstName', label: 'First Name', required: true, aliases: ['first_name', 'firstname', 'name', 'student_name', 'candidate_name', 'cand_name', 'candidate', 'student', 'studentname', 'given_name', 'name_of_candidate', 'name_of_student', 'candidates_name', 'full_name', 'fullname'] },
            { key: 'lastName', label: 'Last Name', required: false, aliases: ['last_name', 'lastname', 'surname', 'family_name'] },
            { key: 'parentName', label: 'Father / Parent Name', required: false, aliases: ['father_name', 'fathername', 'fathers_name', 'father_s_name', 'mother_name', 'mother_s_name', 'parent_name', 'guardian_name'] },
            { key: 'email', label: 'Email Address', required: true, autoGenerated: true, aliases: ['email', 'email_address', 'mail', 'email_id', 'emailid', 'student_email', 'ending_emailid'] },
            { key: 'studentId', label: 'Student ID / Admission No', required: false, aliases: ['student_id', 'studentid', 'admission_number', 'admission_no', 'admn_no', 'adm_no', 'reg_no', 'regn_no', 'registration_no', 'registration_number', 'epunjab_id', 'enrollment_no', 'id_no'] },
            { key: 'phone', label: 'Phone Number', required: false, aliases: ['phone', 'mobile', 'mobile_no', 'contact', 'contact_no', 'phone_number', 'telephone'] },
            { key: 'address', label: 'Residential Address', required: false, aliases: ['address', 'addr', 'residential_address', 'permanent_address', 'residence', 'location', 'city_address', 'student_address'] },
            { key: 'gender', label: 'Gender', required: false, aliases: ['gender', 'sex'] },
            { key: 'rollNumber', label: 'Class Roll No', required: false, aliases: ['class_roll_no', 'roll_number', 'roll_no', 'roll', 'sr_no', 'srno', 's_no', 'sl_no', 'serial_number', 'serial_no', 'r_no', 'rno'] }
        ]
    },
    lab_items: {
        id: 'lab_items',
        label: 'Lab Inventory & Hardware (lab_items)',
        targetEntity: 'inventory',
        fields: [
            { key: 'itemNumber', label: 'Item Number / Asset Tag', required: true, aliases: ['item_number', 'item_no', 'itemnumber', 'asset_id', 'asset_tag', 'tag_no', 'barcode'] },
            { key: 'itemType', label: 'Item Type', required: true, aliases: ['item_type', 'type', 'category', 'hardware_type', 'device_type', 'equipment_type'] },
            { key: 'brand', label: 'Brand / Manufacturer', required: false, aliases: ['brand', 'make', 'manufacturer', 'company', 'vendor'] },
            { key: 'modelNo', label: 'Model Number / Name', required: false, aliases: ['model', 'model_no', 'model_number', 'modelno', 'unit_model'] },
            { key: 'serialNo', label: 'Serial Number', required: false, aliases: ['serial', 'serial_no', 'serial_number', 'serialnumber', 'sn', 's_n'] },
            { key: 'status', label: 'Operating Status', required: false, aliases: ['status', 'condition', 'state', 'health'] },
            { key: 'specs', label: 'Specifications', required: false, aliases: ['specs', 'specifications', 'configuration', 'details', 'hardware_specs', 'description'] },
            { key: 'notes', label: 'Notes / Remarks', required: false, aliases: ['notes', 'remarks', 'comment', 'comments', 'remark'] }
        ]
    },
    classes: {
        id: 'classes',
        label: 'Academic Classes (classes)',
        targetEntity: 'class',
        fields: [
            { key: 'name', label: 'Class Name', required: true, aliases: ['class_name', 'name', 'classname', 'class', 'title'] },
            { key: 'gradeLevel', label: 'Grade / Class Level', required: true, aliases: ['grade_level', 'grade', 'class_level', 'level', 'standard'] },
            { key: 'section', label: 'Section', required: false, aliases: ['section', 'sec', 'division'] },
            { key: 'stream', label: 'Stream / Discipline', required: false, aliases: ['stream', 'branch', 'track'] },
            { key: 'maxStudents', label: 'Capacity / Max Students', required: false, aliases: ['max_students', 'capacity', 'seats', 'limit'] }
        ]
    },
    subjects: {
        id: 'subjects',
        label: 'Curriculum Subjects (subjects)',
        targetEntity: 'subject',
        fields: [
            { key: 'name', label: 'Subject Name', required: true, aliases: ['subject_name', 'name', 'subject', 'course_name', 'title'] },
            { key: 'code', label: 'Subject Code', required: true, aliases: ['code', 'subject_code', 'course_code', 'sub_code'] },
            { key: 'gradeLevel', label: 'Grade Level', required: false, aliases: ['grade_level', 'grade', 'class_level'] },
            { key: 'subjectType', label: 'Subject Type', required: false, aliases: ['type', 'subject_type', 'category'] },
            { key: 'totalTheoryMarks', label: 'Theory Marks', required: false, aliases: ['theory_marks', 'theory', 'total_theory_marks'] },
            { key: 'totalPracticalMarks', label: 'Practical Marks', required: false, aliases: ['practical_marks', 'practical', 'lab_marks', 'total_practical_marks'] }
        ]
    },
    tickets: {
        id: 'tickets',
        label: 'Helpdesk & Lab Tickets (tickets)',
        targetEntity: 'ticket',
        fields: [
            { key: 'title', label: 'Ticket Title / Subject', required: true, aliases: ['title', 'subject', 'ticket_title', 'issue_title', 'heading'] },
            { key: 'description', label: 'Description', required: true, aliases: ['description', 'issue_description', 'problem', 'details', 'body'] },
            { key: 'category', label: 'Category', required: false, aliases: ['category', 'issue_type', 'type', 'ticket_category'] },
            { key: 'priority', label: 'Priority', required: false, aliases: ['priority', 'urgency', 'severity', 'level'] },
            { key: 'status', label: 'Status', required: false, aliases: ['status', 'ticket_status', 'state'] }
        ]
    },
    procurement_requests: {
        id: 'procurement_requests',
        label: 'Procurement Requests (procurement_requests)',
        targetEntity: 'procurement',
        fields: [
            { key: 'itemName', label: 'Item / Equipment Name', required: true, aliases: ['item_name', 'item', 'product_name', 'equipment', 'title'] },
            { key: 'quantity', label: 'Quantity', required: true, aliases: ['quantity', 'qty', 'count', 'units'] },
            { key: 'estimatedCost', label: 'Estimated Cost', required: false, aliases: ['cost', 'estimated_cost', 'price', 'amount', 'budget'] },
            { key: 'priority', label: 'Priority', required: false, aliases: ['priority', 'urgency'] },
            { key: 'justification', label: 'Justification / Purpose', required: false, aliases: ['justification', 'reason', 'purpose', 'remarks'] }
        ]
    }
};

/**
 * Normalize string for key matching
 */
function normalizeStr(str) {
    if (!str) return '';
    return String(str)
        .toLowerCase()
        .trim()
        .replace(/[\s\-_/\\()]+/g, '_')
        .replace(/^_+|_+$/g, '');
}

/**
 * Generate a 3-digit random number between 100 and 999
 */
function generateRandom3Digit() {
    return Math.floor(100 + Math.random() * 900);
}

/**
 * Generate unique student email from first and last names with 3-digit random number collision avoidance
 */
function generateUniqueStudentEmail(firstName, lastName, domain = 'student.school.edu', usedEmails = new Set()) {
    const cleanFirst = String(firstName || 'user').toLowerCase().replace(/[^a-z0-9]/g, '') || 'user';
    const cleanLast = (lastName && String(lastName).toLowerCase() !== 'student' ? String(lastName) : '').toLowerCase().replace(/[^a-z0-9]/g, '');
    const basePrefix = cleanLast ? `${cleanFirst}.${cleanLast}` : cleanFirst;
    const cleanDomain = String(domain).replace(/^@/, '').trim().toLowerCase() || 'student.school.edu';

    let candidate = `${basePrefix}@${cleanDomain}`;
    if (usedEmails.has(candidate)) {
        let attempts = 0;
        while (attempts < 100) {
            const rand3 = generateRandom3Digit();
            const uniqueCand = `${basePrefix}.${rand3}@${cleanDomain}`;
            if (!usedEmails.has(uniqueCand)) {
                candidate = uniqueCand;
                break;
            }
            attempts++;
        }
    }
    usedEmails.add(candidate);
    return candidate;
}

/**
 * Match headers to schema fields enforcing strict 1-to-1 mapping.
 * When multiple CSV columns match the same destination field, the closest match wins
 * and all remaining candidate columns are set to '__ignore__'.
 * Email is excluded from being auto-mapped for users.
 */
function buildSchemaMapping(normHeaders, schema, tableId) {
    const candidates = [];

    for (const { raw, norm } of normHeaders) {
        for (const field of schema.fields) {
            // Rule 2: Do not map email as it is internally generated from name
            if (tableId === 'users' && (field.key === 'email' || field.autoGenerated)) {
                continue;
            }

            // Do not match physical address if header represents email or mail address
            if (field.key === 'address' && (norm.includes('mail') || norm.includes('email'))) {
                continue;
            }

            const normFieldKey = normalizeStr(field.key);
            let score = 0;

            if (norm === normFieldKey) {
                // Direct key match
                score = 100;
            } else {
                for (const alias of field.aliases || []) {
                    const normAlias = normalizeStr(alias);
                    if (norm === normAlias) {
                        // Exact alias match: longer/more specific alias gets slightly higher score
                        score = Math.max(score, 80 + Math.min(15, normAlias.length));
                    } else if (norm.startsWith(`${normAlias}_`) || norm.endsWith(`_${normAlias}`)) {
                        // Prefix or suffix match
                        score = Math.max(score, 60);
                    } else if (norm.length > 3 && (norm.includes(normAlias) || normAlias.includes(norm))) {
                        // Substring inclusion
                        score = Math.max(score, 40);
                    }
                }
            }

            if (score > 0) {
                candidates.push({ raw, norm, fieldKey: field.key, score });
            }
        }
    }

    // Sort candidate matches in descending order of score (closest match first)
    candidates.sort((a, b) => b.score - a.score);

    const mapping = {};
    normHeaders.forEach(({ raw }) => { mapping[raw] = '__ignore__'; });
    const assignedHeaders = new Set();
    const assignedFields = new Set();
    let totalScore = 0;

    for (const cand of candidates) {
        if (!assignedHeaders.has(cand.raw) && !assignedFields.has(cand.fieldKey)) {
            mapping[cand.raw] = cand.fieldKey;
            assignedHeaders.add(cand.raw);
            assignedFields.add(cand.fieldKey);
            totalScore += cand.score;
        }
    }

    return { mapping, totalScore };
}

/**
 * Detect the best-matching database table and produce auto column mappings
 * @param {Array<string>} rawHeaders - List of column headers from file
 * @param {Array<Object>} sampleRows - First few sample rows for inspection
 * @returns {Object} Detection result
 */
function detectTableAndMapping(rawHeaders = [], sampleRows = []) {
    if (!Array.isArray(rawHeaders) || rawHeaders.length === 0) {
        return {
            detectedTable: 'users',
            targetLabel: TABLE_SCHEMAS.users.label,
            confidence: 0,
            columnMapping: {},
            availableFields: TABLE_SCHEMAS.users.fields,
            tableOptions: Object.values(TABLE_SCHEMAS).map(t => ({ id: t.id, label: t.label }))
        };
    }

    const normHeaders = rawHeaders.map(h => ({ raw: h, norm: normalizeStr(h) }));

    let bestTableId = 'users';
    let highestScore = -1;
    let bestMappings = {};

    for (const [tableId, schema] of Object.entries(TABLE_SCHEMAS)) {
        const { mapping, totalScore } = buildSchemaMapping(normHeaders, schema, tableId);
        let score = totalScore;

        // Penalty if required fields are completely missing (except autoGenerated fields like email)
        const mappedKeys = Object.values(mapping);
        const requiredMissing = schema.fields.filter(f => f.required && !f.autoGenerated && !mappedKeys.includes(f.key)).length;
        score -= requiredMissing * 20;

        if (score > highestScore) {
            highestScore = score;
            bestTableId = tableId;
            bestMappings = mapping;
        }
    }

    // Default to users if inventory or other is low confidence
    const selectedSchema = TABLE_SCHEMAS[bestTableId] || TABLE_SCHEMAS.users;

    return {
        detectedTable: bestTableId,
        targetLabel: selectedSchema.label,
        confidence: Math.max(0.1, Math.min(1.0, (highestScore / (normHeaders.length * 100)))),
        columnMapping: bestMappings,
        availableFields: selectedSchema.fields,
        tableOptions: Object.values(TABLE_SCHEMAS).map(t => ({ id: t.id, label: t.label, fields: t.fields }))
    };
}

/**
 * Apply column mapping to transform raw records into normalized DB payload objects
 * @param {Array<Object>} records - Raw file rows
 * @param {Object} columnMapping - Dict of { fileHeader: dbFieldKey }
 * @param {string} targetTable - Table ID
 * @returns {Array<Object>} Cleaned records
 */
function applyMapping(records = [], columnMapping = {}, targetTable = 'users', options = {}) {
    if (!Array.isArray(records)) return [];
    const customEmailDomain = options?.emailDomain ? options.emailDomain.replace(/^@/, '').trim().toLowerCase() : null;
    const usedEmailsInBatch = new Set();

    return records.map((row, idx) => {
        const item = { _originalRowIndex: idx + 1 };

        for (const [fileCol, dbKey] of Object.entries(columnMapping)) {
            if (!dbKey || dbKey === '__ignore__') continue;
            // Never copy email from CSV for users
            if (targetTable === 'users' && dbKey === 'email') continue;

            const val = row[fileCol] !== undefined ? row[fileCol] : row[normalizeStr(fileCol)];
            if (val !== undefined && val !== null) {
                item[dbKey] = typeof val === 'string' ? val.trim() : val;
            }
        }

        // Specific post-processing heuristics
        if (targetTable === 'users') {
            // Split combined student name into firstName and lastName
            if (item.firstName && item.firstName.includes(' ')) {
                const parts = item.firstName.trim().split(/\s+/);
                item.firstName = parts[0];
                if (!item.lastName || item.lastName === 'Student' || item.lastName === item.parentName) {
                    item.lastName = parts.slice(1).join(' ');
                }
            }
            if (!item.lastName) item.lastName = 'Student';

            // Internal Email Generation:
            // Do not map email as it is internally generated from name.
            // If two names generate same email, add 3-digit random number to make unique.
            const domain = customEmailDomain || 'student.school.edu';
            item.email = generateUniqueStudentEmail(item.firstName, item.lastName, domain, usedEmailsInBatch);

            // Normalize gender
            if (item.gender) {
                const g = String(item.gender).toLowerCase();
                if (g.includes('f') || g.includes('girl')) item.gender = 'female';
                else item.gender = 'male';
            } else {
                item.gender = 'male';
            }

            if (item.rollNumber) {
                const rNum = parseInt(item.rollNumber, 10);
                if (!isNaN(rNum)) item.rollNumber = rNum;
            }
            item.role = 'student';
        }

        if (targetTable === 'lab_items') {
            if (!item.itemType) item.itemType = 'pc';
            if (!item.status) item.status = 'active';
            if (!item.itemNumber) item.itemNumber = `ITEM-${Date.now().toString().slice(-4)}-${idx + 1}`;
        }

        if (targetTable === 'classes') {
            if (item.gradeLevel) {
                const gl = parseInt(item.gradeLevel, 10);
                if (!isNaN(gl)) item.gradeLevel = gl;
            }
            if (item.maxStudents) {
                const ms = parseInt(item.maxStudents, 10);
                if (!isNaN(ms)) item.maxStudents = ms;
            }
        }

        if (targetTable === 'subjects') {
            if (item.gradeLevel) {
                const gl = parseInt(item.gradeLevel, 10);
                if (!isNaN(gl)) item.gradeLevel = gl;
            }
            if (item.totalTheoryMarks) {
                const tm = parseInt(item.totalTheoryMarks, 10);
                if (!isNaN(tm)) item.totalTheoryMarks = tm;
            }
            if (item.totalPracticalMarks) {
                const pm = parseInt(item.totalPracticalMarks, 10);
                if (!isNaN(pm)) item.totalPracticalMarks = pm;
            }
        }

        if (targetTable === 'tickets') {
            if (!item.priority) item.priority = 'medium';
            if (!item.status) item.status = 'open';
            if (!item.category) item.category = 'other';
        }

        if (targetTable === 'procurement_requests') {
            if (item.quantity) {
                const q = parseInt(item.quantity, 10);
                if (!isNaN(q)) item.quantity = q;
            }
            if (item.estimatedCost) {
                const c = parseFloat(item.estimatedCost);
                if (!isNaN(c)) item.estimatedCost = c;
            }
        }

        return item;
    });
}

module.exports = {
    TABLE_SCHEMAS,
    detectTableAndMapping,
    applyMapping,
    normalizeStr,
    generateRandom3Digit,
    generateUniqueStudentEmail
};
