'use client';

import React, { useState, useEffect, useMemo } from 'react';
import {
    Database,
    Table,
    GraduationCap,
    Server,
    Laptop,
    Building2,
    CheckCircle2,
    XCircle,
    AlertTriangle,
    ChevronDown,
    ChevronRight,
    Search,
    CheckSquare,
    Square,
    Loader2,
    ArrowRight,
    RefreshCw,
    ExternalLink,
    FileSpreadsheet,
    Copy,
    Check
} from 'lucide-react';
import api, { classesAPI, labsAPI } from '@/lib/api';
import toast from 'react-hot-toast';

// Available field definitions per target table
const TABLE_FIELD_DEFINITIONS = {
    users: [
        { key: 'firstName', label: 'First Name', required: true, desc: 'Student first name' },
        { key: 'lastName', label: 'Last Name', required: false, desc: 'Student surname / last name' },
        { key: 'parentName', label: 'Father / Parent Name', required: false, desc: 'Father / guardian name' },
        { key: 'email', label: 'Email Address (Auto-Generated)', required: false, autoGenerated: true, desc: 'Internally generated; CSV email is not mapped' },
        { key: 'studentId', label: 'Student / Admission No', required: false, desc: 'Unique admission / registration ID' },
        { key: 'phone', label: 'Contact Phone', required: false, desc: 'Mobile / parent contact' },
        { key: 'address', label: 'Residential Address', required: false, desc: 'Student address / residence' },
        { key: 'rollNumber', label: 'Roll Number', required: false, desc: 'Class roll number' },
        { key: 'gender', label: 'Gender', required: false, desc: 'Male / Female' }
    ],
    lab_items: [
        { key: 'itemNumber', label: 'Item / Asset Number', required: true, desc: 'Asset identifier' },
        { key: 'itemType', label: 'Equipment Type', required: true, desc: 'pc, monitor, keyboard, switch, etc.' },
        { key: 'brand', label: 'Brand / Make', required: false, desc: 'Dell, HP, Lenovo, Cisco, etc.' },
        { key: 'modelNo', label: 'Model Number', required: false, desc: 'Hardware model' },
        { key: 'serialNo', label: 'Serial Number', required: false, desc: 'Hardware serial tag' },
        { key: 'status', label: 'Status / Condition', required: false, desc: 'active, maintenance, inactive' },
        { key: 'specs', label: 'Specifications', required: false, desc: 'RAM, CPU, storage, ports' }
    ],
    classes: [
        { key: 'name', label: 'Class Name', required: true, desc: 'e.g. 11 Non-Medical A' },
        { key: 'gradeLevel', label: 'Grade Level', required: true, desc: 'e.g. 10, 11, 12' },
        { key: 'section', label: 'Section', required: false, desc: 'e.g. A, B, C' },
        { key: 'stream', label: 'Stream', required: false, desc: 'Medical, Non-Medical, Arts, Commerce' },
        { key: 'maxStudents', label: 'Capacity / Max Students', required: false, desc: 'Maximum student limit' }
    ],
    subjects: [
        { key: 'name', label: 'Subject Name', required: true, desc: 'e.g. Computer Science' },
        { key: 'code', label: 'Subject Code', required: true, desc: 'e.g. CS101' },
        { key: 'gradeLevel', label: 'Grade Level', required: false, desc: 'e.g. 11' },
        { key: 'subjectType', label: 'Subject Type', required: false, desc: 'Theory / Practical / Vocational' },
        { key: 'totalTheoryMarks', label: 'Theory Marks', required: false, desc: 'Max theory marks' },
        { key: 'totalPracticalMarks', label: 'Practical Marks', required: false, desc: 'Max practical marks' }
    ],
    tickets: [
        { key: 'title', label: 'Ticket Title', required: true, desc: 'Subject / issue summary' },
        { key: 'description', label: 'Description', required: true, desc: 'Detailed explanation of problem' },
        { key: 'category', label: 'Category', required: false, desc: 'hardware, software, network, other' },
        { key: 'priority', label: 'Priority', required: false, desc: 'low, medium, high, urgent' },
        { key: 'status', label: 'Status', required: false, desc: 'open, in_progress, resolved, closed' }
    ],
    procurement_requests: [
        { key: 'itemName', label: 'Item Name', required: true, desc: 'Equipment or supply requested' },
        { key: 'quantity', label: 'Quantity', required: true, desc: 'Number of units needed' },
        { key: 'estimatedCost', label: 'Estimated Cost', required: false, desc: 'Approximate price' },
        { key: 'priority', label: 'Priority', required: false, desc: 'low, medium, high' },
        { key: 'justification', label: 'Justification', required: false, desc: 'Reason for procurement' }
    ]
};

export default function GenericDataImportConfirmCard({ action }) {
    if (!action) return null;

    const detectedTable = action.targetTable || (action.actionType === 'student_import' ? 'users' : 'lab_items');
    const [targetTable, setTargetTable] = useState(detectedTable);
    const [records, setRecords] = useState(() => (action.records || []).map((r, idx) => ({ ...r, _selected: true, _idx: idx })));
    const [columnMapping, setColumnMapping] = useState(() => action.columnMapping || {});
    const [isMappingExpanded, setIsMappingExpanded] = useState(true);
    const [searchQuery, setSearchQuery] = useState('');
    const [loading, setLoading] = useState(false);
    const [isConfirmed, setIsConfirmed] = useState(action.isConfirmed || false);
    const [importResult, setImportResult] = useState(() => action.importResult || null);
    const [showErrorDetails, setShowErrorDetails] = useState(true);
    const [copiedError, setCopiedError] = useState(false);

    // Target Class selector state (for students)
    const [availableClasses, setAvailableClasses] = useState(action.classes || []);
    const [selectedClassId, setSelectedClassId] = useState(action.targetClassId || action.classId || '');

    // Target Lab selector state (for lab items)
    const [availableLabs, setAvailableLabs] = useState(action.labs || action.availableLabs || []);
    const [selectedLabId, setSelectedLabId] = useState(action.targetLabId || action.labId || '');

    // Fetch classes or labs if needed
    useEffect(() => {
        if (targetTable === 'users' && availableClasses.length === 0) {
            classesAPI.getAll({ limit: 100 }).then(res => {
                const list = res.data?.data?.classes || res.data?.data || [];
                if (Array.isArray(list) && list.length > 0) {
                    setAvailableClasses(list);
                    if (!selectedClassId) setSelectedClassId(list[0].id);
                }
            }).catch(() => {});
        } else if (targetTable === 'lab_items' && availableLabs.length === 0) {
            labsAPI.getAll().then(res => {
                const list = res.data?.data?.labs || res.data?.data || [];
                if (Array.isArray(list) && list.length > 0) {
                    setAvailableLabs(list);
                    if (!selectedLabId) setSelectedLabId(list[0].id);
                }
            }).catch(() => {});
        }
    }, [targetTable]);

    // Source headers from records
    const sourceHeaders = useMemo(() => {
        if (!records.length) return [];
        const first = records[0];
        return Object.keys(first).filter(k => !k.startsWith('_'));
    }, [records]);

    const tableOptions = useMemo(() => {
        if (action.tableOptions && Array.isArray(action.tableOptions) && action.tableOptions.length > 0) {
            return action.tableOptions;
        }
        return [
            { id: 'users', label: 'Students / Users (users)' },
            { id: 'lab_items', label: 'Lab Inventory & Hardware (lab_items)' },
            { id: 'classes', label: 'Academic Classes (classes)' },
            { id: 'subjects', label: 'Curriculum Subjects (subjects)' },
            { id: 'tickets', label: 'Helpdesk & Lab Tickets (tickets)' },
            { id: 'procurement_requests', label: 'Procurement Requests (procurement_requests)' }
        ];
    }, [action.tableOptions]);

    // Table field options
    const tableFields = useMemo(() => {
        const opt = tableOptions.find(t => t.id === targetTable);
        if (opt?.fields && Array.isArray(opt.fields) && opt.fields.length > 0) {
            return opt.fields;
        }
        return TABLE_FIELD_DEFINITIONS[targetTable] || action.availableFields || [];
    }, [targetTable, tableOptions, action.availableFields]);

    const handleTableChange = (newTable) => {
        setTargetTable(newTable);
        const fields = TABLE_FIELD_DEFINITIONS[newTable] || tableOptions.find(t => t.id === newTable)?.fields || [];
        const candidates = [];

        sourceHeaders.forEach(h => {
            const normH = h.toLowerCase().replace(/[^a-z0-9]/g, '');
            for (const f of fields) {
                if (newTable === 'users' && (f.key === 'email' || f.autoGenerated)) continue;
                const normK = f.key.toLowerCase().replace(/[^a-z0-9]/g, '');
                let score = 0;
                if (normH === normK) {
                    score = 100;
                } else {
                    const aliases = (f.aliases || []).map(a => a.toLowerCase().replace(/[^a-z0-9]/g, ''));
                    for (const a of aliases) {
                        if (normH === a) {
                            score = Math.max(score, 80 + Math.min(15, a.length));
                        } else if (normH.startsWith(`${a}_`) || normH.endsWith(`_${a}`)) {
                            score = Math.max(score, 60);
                        } else if (normH.length > 3 && (normH.includes(a) || a.includes(normH))) {
                            score = Math.max(score, 40);
                        }
                    }
                }
                if (score > 0) {
                    candidates.push({ header: h, fieldKey: f.key, score });
                }
            }
        });

        // Closest match wins, remaining candidates ignored
        candidates.sort((a, b) => b.score - a.score);
        const newMapping = {};
        sourceHeaders.forEach(h => { newMapping[h] = '__ignore__'; });
        const assignedHeaders = new Set();
        const assignedFields = new Set();

        for (const c of candidates) {
            if (!assignedHeaders.has(c.header) && !assignedFields.has(c.fieldKey)) {
                newMapping[c.header] = c.fieldKey;
                assignedHeaders.add(c.header);
                assignedFields.add(c.fieldKey);
            }
        }

        setColumnMapping(newMapping);
    };

    // Filtered records for preview
    const filteredRecords = useMemo(() => {
        if (!searchQuery.trim()) return records;
        const q = searchQuery.toLowerCase();
        return records.filter(r =>
            Object.entries(r).some(([k, v]) => !k.startsWith('_') && String(v).toLowerCase().includes(q))
        );
    }, [records, searchQuery]);

    const selectedCount = records.filter(r => r._selected).length;

    const toggleSelectAll = () => {
        const allSelected = selectedCount === records.length;
        setRecords(prev => prev.map(r => ({ ...r, _selected: !allSelected })));
    };

    const toggleRow = (idx) => {
        setRecords(prev => prev.map(r => r._idx === idx ? { ...r, _selected: !r._selected } : r));
    };

    const handleMappingChange = (sourceHeader, targetField) => {
        setColumnMapping(prev => {
            const next = { ...prev };
            if (targetField === '__ignore__' || !targetField) {
                delete next[sourceHeader];
            } else {
                // Ensure 1-to-1: if another column had this same targetField, unassign it
                for (const [col, dbKey] of Object.entries(next)) {
                    if (col !== sourceHeader && dbKey === targetField) {
                        delete next[col];
                    }
                }
                next[sourceHeader] = targetField;
            }
            return next;
        });
    };

    // Confirm Import action
    const handleConfirmImport = async () => {
        const itemsToImport = records.filter(r => r._selected);
        if (itemsToImport.length === 0) {
            toast.error('Please select at least one record to import');
            return;
        }

        setLoading(true);
        try {
            const res = await api.post('/admin/chatbot/load-data', {
                actionType: targetTable === 'users' ? 'student_import' : targetTable === 'lab_items' ? 'inventory_import' : 'generic_import',
                targetTable,
                classId: selectedClassId,
                labId: selectedLabId,
                records: itemsToImport,
                columnMapping,
                emailDomain: action.emailDomain
            });

            if (res.data?.success) {
                setIsConfirmed(true);
                setImportResult(res.data);
                toast.success(res.data.message || `Successfully imported ${res.data.count} records!`);

                if (targetTable === 'lab_items') {
                    window.dispatchEvent(new CustomEvent('lab-items-updated'));
                } else if (targetTable === 'users') {
                    window.dispatchEvent(new CustomEvent('users-updated'));
                }
            } else {
                toast.error(res.data?.message || 'Import failed');
            }
        } catch (err) {
            console.error('Import error:', err);
            toast.error(err.response?.data?.message || err.message || 'Failed to import records');
        } finally {
            setLoading(false);
        }
    };

    const copyErrorLog = () => {
        if (!importResult?.failedRows?.length) return;
        const text = importResult.failedRows.map(f => `Row ${f.row} [${f.identifier}]: ${f.error}`).join('\n');
        navigator.clipboard.writeText(text);
        setCopiedError(true);
        setTimeout(() => setCopiedError(false), 2000);
        toast.success('Error log copied to clipboard');
    };

    // Theme and icon per table
    const tableMeta = {
        users: {
            title: 'Student Roster Import',
            icon: <GraduationCap className="w-4 h-4 text-white" />,
            badge: 'Students & Users Table',
            gradient: 'from-blue-600 via-indigo-600 to-violet-600',
            bgBadge: 'bg-blue-50 text-blue-700 border-blue-200',
            viewLink: selectedClassId ? `/admin/classes/${selectedClassId}` : '/admin/classes'
        },
        lab_items: {
            title: 'Lab Inventory Import',
            icon: <Server className="w-4 h-4 text-white" />,
            badge: 'Lab Equipment Table',
            gradient: 'from-emerald-600 via-teal-600 to-cyan-700',
            bgBadge: 'bg-emerald-50 text-emerald-700 border-emerald-200',
            viewLink: selectedLabId ? `/admin/labs/${selectedLabId}` : '/admin/labs'
        },
        classes: {
            title: 'Class Registry Import',
            icon: <Building2 className="w-4 h-4 text-white" />,
            badge: 'Classes Table',
            gradient: 'from-indigo-600 via-purple-600 to-pink-600',
            bgBadge: 'bg-purple-50 text-purple-700 border-purple-200',
            viewLink: '/admin/classes'
        },
        subjects: {
            title: 'Subject Curriculum Import',
            icon: <Database className="w-4 h-4 text-white" />,
            badge: 'Subjects Table',
            gradient: 'from-purple-600 via-indigo-600 to-blue-600',
            bgBadge: 'bg-indigo-50 text-indigo-700 border-indigo-200',
            viewLink: '/admin/subjects'
        }
    }[targetTable] || {
        title: 'Data Table Import',
        icon: <Database className="w-4 h-4 text-white" />,
        badge: `${targetTable} Table`,
        gradient: 'from-slate-700 via-indigo-700 to-slate-800',
        bgBadge: 'bg-slate-100 text-slate-700 border-slate-200',
        viewLink: '/admin'
    };

    return (
        <div className="mt-3 rounded-2xl bg-white dark:bg-slate-900 border border-indigo-200 dark:border-indigo-800/70 shadow-lg overflow-hidden text-xs">
            {/* Header */}
            <div className={`px-4 py-3 bg-gradient-to-r ${tableMeta.gradient} text-white flex items-center justify-between`}>
                <div className="flex items-center gap-2.5">
                    <div className="w-8 h-8 rounded-xl bg-white/20 backdrop-blur flex items-center justify-center">
                        {tableMeta.icon}
                    </div>
                    <div>
                        <div className="flex items-center gap-2">
                            <h4 className="font-bold text-sm leading-tight">{tableMeta.title}</h4>
                            <span className="px-2 py-0.5 rounded-full bg-white/20 text-[10px] font-semibold">
                                {action.sourceDocument || action.fileName || 'Referenced File'}
                            </span>
                        </div>
                        <p className="text-[11px] text-white/80 mt-0.5">
                            {records.length} records detected • Auto-detected target: <strong>{targetTable}</strong>
                        </p>
                    </div>
                </div>

                <div className="flex items-center gap-2">
                    <span className="px-2.5 py-1 rounded-full bg-black/20 text-[11px] font-semibold">
                        {selectedCount}/{records.length} Selected
                    </span>
                </div>
            </div>

            {/* Target Destination & Table Selector Bar */}
            <div className="px-4 py-2.5 bg-slate-50 dark:bg-slate-800/60 border-b border-slate-200 dark:border-slate-800 flex flex-wrap items-center justify-between gap-3">
                <div className="flex items-center gap-4 flex-wrap">
                    {/* If users/students, show target class selector */}
                    {targetTable === 'users' && (
                        <div className="flex items-center gap-1.5">
                            <label className="font-semibold text-slate-700 dark:text-slate-300">Enroll Into Class:</label>
                            <select
                                value={selectedClassId}
                                disabled={isConfirmed}
                                onChange={(e) => setSelectedClassId(e.target.value)}
                                className="px-2.5 py-1 bg-white dark:bg-slate-800 border border-slate-300 dark:border-slate-700 rounded-lg text-xs font-medium focus:ring-2 focus:ring-indigo-500 focus:outline-none"
                            >
                                {availableClasses.map(c => (
                                    <option key={c.id} value={c.id}>
                                        🏫 {c.name} {c.section ? `(${c.section})` : ''}
                                    </option>
                                ))}
                            </select>
                        </div>
                    )}

                    {/* If lab items, show target lab selector */}
                    {targetTable === 'lab_items' && (
                        <div className="flex items-center gap-1.5">
                            <label className="font-semibold text-slate-700 dark:text-slate-300">Target Lab:</label>
                            <select
                                value={selectedLabId}
                                disabled={isConfirmed}
                                onChange={(e) => setSelectedLabId(e.target.value)}
                                className="px-2.5 py-1 bg-white dark:bg-slate-800 border border-slate-300 dark:border-slate-700 rounded-lg text-xs font-medium focus:ring-2 focus:ring-teal-500 focus:outline-none"
                            >
                                {availableLabs.map(l => (
                                    <option key={l.id} value={l.id}>
                                        🏢 {l.name}
                                    </option>
                                ))}
                            </select>
                        </div>
                    )}

                    <div className="flex items-center gap-1.5">
                        <label className="font-semibold text-slate-700 dark:text-slate-300">Target Table:</label>
                        <select
                            value={targetTable}
                            disabled={isConfirmed}
                            onChange={(e) => handleTableChange(e.target.value)}
                            className="px-2.5 py-1 bg-white dark:bg-slate-800 border border-slate-300 dark:border-slate-700 rounded-lg text-xs font-semibold text-indigo-700 dark:text-indigo-300 shadow-xs focus:ring-2 focus:ring-indigo-500 focus:outline-none"
                        >
                            {tableOptions.map(t => (
                                <option key={t.id} value={t.id}>
                                    🗄️ {t.label || t.id}
                                </option>
                            ))}
                        </select>
                    </div>
                </div>

                <div className="flex items-center gap-3">
                    <button
                        type="button"
                        onClick={() => setIsMappingExpanded(!isMappingExpanded)}
                        className="text-xs font-semibold text-indigo-600 dark:text-indigo-400 hover:text-indigo-800 dark:hover:text-indigo-300 flex items-center gap-1 transition"
                    >
                        {isMappingExpanded ? <ChevronDown className="w-3.5 h-3.5" /> : <ChevronRight className="w-3.5 h-3.5" />}
                        Column Mapping ({Object.keys(columnMapping).filter(k => columnMapping[k] && columnMapping[k] !== '__ignore__').length} mapped)
                    </button>
                    <button
                        type="button"
                        disabled={isConfirmed}
                        onClick={toggleSelectAll}
                        className="text-xs font-medium text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-100 transition"
                    >
                        {selectedCount === records.length ? 'Deselect All' : 'Select All'}
                    </button>
                </div>
            </div>

            {/* Side-by-Side Column Mapping Section */}
            {isMappingExpanded && (
                <div className="p-4 bg-slate-50/90 dark:bg-slate-900/80 border-b border-indigo-100 dark:border-indigo-900/50">
                    <div className="flex items-center justify-between mb-3">
                        <div className="flex items-center gap-2">
                            <div className="w-6 h-6 rounded-lg bg-indigo-600 text-white flex items-center justify-center">
                                <FileSpreadsheet className="w-3.5 h-3.5" />
                            </div>
                            <div>
                                <span className="font-bold text-slate-800 dark:text-slate-100 text-xs">
                                    Side-by-Side Column Matching (AI-Auto-Mapped)
                                </span>
                                <p className="text-[11px] text-slate-500 dark:text-slate-400">
                                    Review and customize how uploaded file columns map into destination <strong>{targetTable}</strong> fields.
                                </p>
                            </div>
                        </div>
                        <span className="px-2.5 py-1 rounded-full text-[10px] font-semibold bg-indigo-100 text-indigo-800 dark:bg-indigo-950 dark:text-indigo-300">
                            {Object.keys(columnMapping).filter(k => columnMapping[k] && columnMapping[k] !== '__ignore__').length} of {sourceHeaders.length} Columns Mapped
                        </span>
                    </div>

                    <div className="overflow-x-auto rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 shadow-xs">
                        <table className="w-full text-left text-xs border-collapse">
                            <thead>
                                <tr className="bg-slate-100 dark:bg-slate-800 border-b border-slate-200 dark:border-slate-800 text-slate-600 dark:text-slate-400 font-semibold text-[11px]">
                                    <th className="py-2.5 px-3 w-5/12">📄 Uploaded File Column</th>
                                    <th className="py-2.5 px-2 w-1/12 text-center">AI Match</th>
                                    <th className="py-2.5 px-3 w-5/12">🗄️ Destination Table Field ({targetTable})</th>
                                    <th className="py-2.5 px-3 w-1/12 text-center">Status</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-slate-100 dark:divide-slate-800/60">
                                {sourceHeaders.map(header => {
                                    const currentTarget = columnMapping[header] || '';
                                    const sampleVal = records[0]?.[header];
                                    const isMapped = currentTarget && currentTarget !== '__ignore__';

                                    return (
                                        <tr key={header} className="hover:bg-indigo-50/30 dark:hover:bg-indigo-950/20 transition-colors">
                                            <td className="py-2.5 px-3 align-middle">
                                                <div className="flex flex-col">
                                                    <span className="font-mono font-bold text-slate-800 dark:text-slate-200 text-xs">
                                                        {header}
                                                    </span>
                                                    {sampleVal !== undefined && (
                                                        <span className="text-[10px] text-slate-400 truncate max-w-xs" title={String(sampleVal)}>
                                                            Sample: <strong className="text-slate-600 dark:text-slate-300 font-normal">"{String(sampleVal).slice(0, 35)}{String(sampleVal).length > 35 ? '...' : ''}"</strong>
                                                        </span>
                                                    )}
                                                </div>
                                            </td>
                                            <td className="py-2.5 px-2 text-center align-middle">
                                                <div className="inline-flex items-center justify-center w-6 h-6 rounded-full bg-indigo-50 dark:bg-indigo-950/60 text-indigo-600 dark:text-indigo-400">
                                                    <ArrowRight className="w-3.5 h-3.5" />
                                                </div>
                                            </td>
                                            <td className="py-2.5 px-3 align-middle">
                                                <select
                                                    value={currentTarget || '__ignore__'}
                                                    disabled={isConfirmed}
                                                    onChange={(e) => handleMappingChange(header, e.target.value)}
                                                    className="w-full text-xs px-2.5 py-1.5 bg-slate-50 dark:bg-slate-800 border border-slate-300 dark:border-slate-700 rounded-lg text-slate-800 dark:text-slate-100 font-medium focus:ring-2 focus:ring-indigo-500 focus:outline-none"
                                                >
                                                    <option value="__ignore__">-- Ignore Column (Do Not Ingest) --</option>
                                                    {tableFields.map(f => {
                                                        if (targetTable === 'users' && (f.key === 'email' || f.autoGenerated)) {
                                                            return (
                                                                <option key={f.key} value="__ignore__" disabled>
                                                                    {f.label} (Internally Generated - Not Mapped)
                                                                </option>
                                                            );
                                                        }
                                                        return (
                                                            <option key={f.key} value={f.key}>
                                                                {f.label} {f.required ? '(*required)' : ''}
                                                            </option>
                                                        );
                                                    })}
                                                </select>
                                            </td>
                                            <td className="py-2.5 px-3 text-center align-middle whitespace-nowrap">
                                                {isMapped ? (
                                                    <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold bg-emerald-100 dark:bg-emerald-950/60 text-emerald-700 dark:text-emerald-300 border border-emerald-200 dark:border-emerald-800">
                                                        <Check className="w-2.5 h-2.5" />
                                                        Mapped
                                                    </span>
                                                ) : (
                                                    <span className="inline-flex items-center px-2 py-0.5 rounded-full text-[10px] font-semibold bg-slate-100 dark:bg-slate-800 text-slate-500 dark:text-slate-400">
                                                        Ignored
                                                    </span>
                                                )}
                                            </td>
                                        </tr>
                                    );
                                })}
                            </tbody>
                        </table>
                    </div>
                </div>
            )}

            {/* Table Preview Toolbar */}
            <div className="px-3.5 py-2 bg-white dark:bg-slate-900 border-b border-slate-200 dark:border-slate-800 flex items-center justify-between gap-3">
                <div className="relative flex-1 max-w-xs">
                    <Search className="w-3.5 h-3.5 absolute left-2.5 top-1/2 -translate-y-1/2 text-slate-400" />
                    <input
                        type="text"
                        placeholder="Search extracted rows..."
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                        className="w-full pl-8 pr-3 py-1 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg text-xs focus:ring-1 focus:ring-indigo-500 focus:outline-none text-slate-800 dark:text-slate-200"
                    />
                </div>

                <div className="text-[11px] text-slate-500 dark:text-slate-400 font-medium">
                    Showing {filteredRecords.length} of {records.length} records
                </div>
            </div>

            {/* Records Preview Table */}
            <div className="max-h-60 overflow-y-auto overflow-x-auto border-b border-slate-200 dark:border-slate-800">
                <table className="w-full text-left text-[11px] border-collapse">
                    <thead className="bg-slate-100 dark:bg-slate-800/80 sticky top-0 z-10 text-slate-600 dark:text-slate-400 font-bold border-b border-slate-200 dark:border-slate-800">
                        <tr>
                            <th className="p-2 w-8 text-center">
                                <input
                                    type="checkbox"
                                    checked={selectedCount === records.length && records.length > 0}
                                    onChange={toggleSelectAll}
                                    disabled={isConfirmed}
                                    className="rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"
                                />
                            </th>
                            <th className="p-2 w-10 text-center text-slate-400">#</th>
                            {sourceHeaders.map(h => (
                                <th key={h} className="p-2 whitespace-nowrap">
                                    <div className="flex flex-col">
                                        <span className="font-semibold">{h}</span>
                                        {columnMapping[h] && (
                                            <span className="text-[9px] font-mono text-indigo-600 dark:text-indigo-400 font-normal">
                                                → {columnMapping[h]}
                                            </span>
                                        )}
                                    </div>
                                </th>
                            ))}
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                        {filteredRecords.length === 0 ? (
                            <tr>
                                <td colSpan={sourceHeaders.length + 2} className="p-6 text-center text-slate-400">
                                    No records match your search filter
                                </td>
                            </tr>
                        ) : (
                            filteredRecords.map((r, i) => (
                                <tr
                                    key={r._idx}
                                    onClick={() => !isConfirmed && toggleRow(r._idx)}
                                    className={`cursor-pointer transition ${
                                        r._selected
                                            ? 'bg-white dark:bg-slate-900 hover:bg-slate-50 dark:hover:bg-slate-800/60'
                                            : 'bg-slate-50/70 dark:bg-slate-950/40 text-slate-400 opacity-60'
                                    }`}
                                >
                                    <td className="p-2 text-center" onClick={(e) => e.stopPropagation()}>
                                        <input
                                            type="checkbox"
                                            checked={!!r._selected}
                                            onChange={() => toggleRow(r._idx)}
                                            disabled={isConfirmed}
                                            className="rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"
                                        />
                                    </td>
                                    <td className="p-2 text-center text-slate-400 font-mono text-[10px]">
                                        {r._idx + 1}
                                    </td>
                                    {sourceHeaders.map(h => (
                                        <td key={h} className="p-2 whitespace-nowrap max-w-[180px] truncate text-slate-700 dark:text-slate-300">
                                            {String(r[h] ?? '')}
                                        </td>
                                    ))}
                                </tr>
                            ))
                        )}
                    </tbody>
                </table>
            </div>

            {/* Post-Import Result or Action Footer */}
            {isConfirmed && importResult ? (
                <div className="p-4 bg-emerald-50/60 dark:bg-emerald-950/30 border-t border-emerald-200 dark:border-emerald-800">
                    <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2.5">
                            <div className="w-8 h-8 rounded-full bg-emerald-500 text-white flex items-center justify-center">
                                <CheckCircle2 className="w-5 h-5" />
                            </div>
                            <div>
                                <h5 className="font-bold text-emerald-900 dark:text-emerald-200 text-xs">
                                    Import Completed Successfully!
                                </h5>
                                <p className="text-[11px] text-emerald-700 dark:text-emerald-300">
                                    Loaded <strong>{importResult.count}</strong> records into <strong>{targetTable}</strong> table.
                                    {importResult.failedCount > 0 && (
                                        <span className="ml-1 text-amber-700 dark:text-amber-300 font-medium">
                                            ({importResult.failedCount} rows failed)
                                        </span>
                                    )}
                                </p>
                            </div>
                        </div>

                        <div className="flex items-center gap-2">
                            {tableMeta.viewLink && (
                                <a
                                    href={tableMeta.viewLink}
                                    className="px-3 py-1.5 rounded-xl bg-emerald-600 text-white font-semibold text-xs flex items-center gap-1.5 hover:bg-emerald-700 shadow-xs transition"
                                >
                                    <span>View Records</span>
                                    <ExternalLink className="w-3.5 h-3.5" />
                                </a>
                            )}
                        </div>
                    </div>

                    {/* Row-by-Row Failure Log (if any rows failed) */}
                    {importResult.failedCount > 0 && importResult.failedRows?.length > 0 && (
                        <div className="mt-3 p-3 rounded-xl bg-red-50/80 dark:bg-red-950/40 border border-red-200 dark:border-red-900/60">
                            <div className="flex items-center justify-between mb-2">
                                <span className="font-bold text-red-900 dark:text-red-300 flex items-center gap-1 text-xs">
                                    <AlertTriangle className="w-3.5 h-3.5 text-red-600" />
                                    Failed Rows Detail ({importResult.failedRows.length} errors)
                                </span>
                                <div className="flex items-center gap-2">
                                    <button
                                        onClick={copyErrorLog}
                                        className="text-[10px] text-red-700 dark:text-red-300 hover:underline flex items-center gap-1 font-medium"
                                    >
                                        {copiedError ? <Check className="w-3 h-3 text-emerald-600" /> : <Copy className="w-3 h-3" />}
                                        {copiedError ? 'Copied' : 'Copy Log'}
                                    </button>
                                    <button
                                        onClick={() => setShowErrorDetails(!showErrorDetails)}
                                        className="text-[10px] text-red-700 dark:text-red-300 hover:underline font-medium"
                                    >
                                        {showErrorDetails ? 'Hide' : 'Show'}
                                    </button>
                                </div>
                            </div>

                            {showErrorDetails && (
                                <div className="max-h-40 overflow-y-auto divide-y divide-red-200 dark:divide-red-900/40 text-[11px] font-mono">
                                    {importResult.failedRows.map((f, i) => (
                                        <div key={i} className="py-1.5 flex items-start justify-between gap-3 text-red-800 dark:text-red-200">
                                            <div className="flex items-center gap-2">
                                                <span className="px-1.5 py-0.2 rounded bg-red-200 dark:bg-red-900 text-red-900 dark:text-red-100 font-bold text-[10px]">
                                                    Row {f.row}
                                                </span>
                                                <span className="font-medium text-slate-700 dark:text-slate-300">
                                                    {f.identifier}
                                                </span>
                                            </div>
                                            <span className="text-red-600 dark:text-red-400 text-right">
                                                {f.error}
                                            </span>
                                        </div>
                                    ))}
                                </div>
                            )}
                        </div>
                    )}
                </div>
            ) : (
                <div className="p-3.5 bg-slate-50 dark:bg-slate-900 flex items-center justify-between gap-3">
                    <div className="text-[11px] text-slate-500 dark:text-slate-400">
                        {selectedCount === 0 ? (
                            <span className="text-amber-600 font-medium">Select at least one record to enable import</span>
                        ) : (
                            <span>Ready to load <strong>{selectedCount}</strong> records into <strong>{targetTable}</strong></span>
                        )}
                    </div>

                    <div className="flex items-center gap-2">
                        <button
                            type="button"
                            onClick={handleConfirmImport}
                            disabled={selectedCount === 0 || loading || isConfirmed}
                            className="px-4 py-2 rounded-xl bg-gradient-to-r from-indigo-600 to-violet-600 hover:from-indigo-700 hover:to-violet-700 text-white font-bold text-xs shadow-md shadow-indigo-500/20 flex items-center gap-2 transition disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                            {loading ? (
                                <>
                                    <Loader2 className="w-3.5 h-3.5 animate-spin" />
                                    <span>Importing Records...</span>
                                </>
                            ) : (
                                <>
                                    <CheckCircle2 className="w-3.5 h-3.5" />
                                    <span>Confirm & Import ({selectedCount} Records)</span>
                                </>
                            )}
                        </button>
                    </div>
                </div>
            )}
        </div>
    );
}
